version: "3"
services:
    backend:
        container_name: travel_log_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: travel_log/server
        ports:
            - "1337:1337"
        volumes:
            - ./server:/usr/src/app
