version: "3"
services:
    backend:
        container_name: button_vanilla_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: button_vanilla/server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/usr/src/app
